-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Clerk user ID (string)
  total_amount integer not null,
  status text not null default 'pending', -- 'pending', 'completed', 'cancelled'
  shipping_address jsonb,
  payment_id text, -- PortOne payment ID
  payment_method text, -- 'CARD', 'VIRTUAL_ACCOUNT'
  payment_info jsonb, -- Full payment response from PortOne
  vbank_num text, -- Virtual account number
  vbank_name text, -- Bank name
  vbank_holder text, -- Account holder
  vbank_date timestamp with time zone, -- Deposit deadline
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items Table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null,
  price integer not null, -- Price at time of purchase
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Policies
create policy "Users can see their own orders"
on public.orders
for select
to authenticated
using (user_id = auth.jwt() ->> 'sub'); -- Typically Clerk sub is passed to Supabase via JWT if linked

-- For development, allow insert (simplified)
create policy "Authenticated users can create orders"
on public.orders
for insert
to authenticated
with check (true);

create policy "Authenticated users can see their order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1 from public.orders
    where id = order_items.order_id
    and user_id = auth.jwt() ->> 'sub'
  )
);

create policy "Authenticated users can insert order items"
on public.order_items
for insert
to authenticated
with check (true);
