-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price integer not null,
  images text[] not null,
  category text not null,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security
alter table public.products enable row level security;

-- Create Policy to allow public read access
create policy "Allow public read access"
on public.products
for select
to public
using (true);

-- Insert Dummy Data (Anti-gravity Concept)
insert into public.products (name, description, price, images, category, stock)
values
  (
    'Zero Gravity Ring',
    'A ring designed to feel weightless on your finger. Crafted with aerogel-infused silver.',
    89000,
    ARRAY['https://images.unsplash.com/photo-1605100804763-ebea4663163c?auto=format&fit=crop&q=80&w=800'],
    'Ring',
    15
  ),
  (
    'Levitation Necklace',
    'Suspended aesthetics. The centerpiece appears to float above the chain.',
    125000,
    ARRAY['https://images.unsplash.com/photo-1599643478518-17488fbbcd75?auto=format&fit=crop&q=80&w=800'],
    'Necklace',
    8
  ),
  (
    'Nebula Ear Cuff',
    'Inspired by cosmic dust. No piercing required, purely magnetic.',
    45000,
    ARRAY['https://images.unsplash.com/photo-1635767798638-3e2523422dc0?auto=format&fit=crop&q=80&w=800'],
    'Earring',
    20
  ),
  (
    'Void Bracelet',
    'Absorbs light, reflects style. Matte black finish with hidden clasp.',
    68000,
    ARRAY['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=800'],
    'Bracelet',
    12
  ),
  (
    'Orbit Ring Set',
    'Three rings that interlock but never touch.',
    150000,
    ARRAY['https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800'],
    'Ring',
    5
  );
