-- Create Users Table for storing Points
-- Note: Authentication is handled by Clerk, this table purely extends user data for our app logic.

create table public.users (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique,
  email text,
  points integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.users enable row level security;

-- Policies
create policy "Users can read their own data"
on public.users for select
using (auth.uid()::text = clerk_id OR true); -- Allowing public read for simplicity in this demo, realistically should be secured or accessed via Service Role

create policy "Service Role can manage all users"
on public.users for all
using (true)
with check (true);
